// FRAC-KG graph backup -- exported from the live Neo4j instance by CI
// Exported : 2026-08-27T14:41:15Z
// Source   : neo4j+s://a91d1092.databases.neo4j.io
// Nodes    : 245   Relationships: 783
// Replay   : set NEO4J_URI/USER/PASSWORD[/DATABASE], then
//            python scripts/restore_backup.py backups/FRAC_KG_latest.cypher --reset

// ---------- Constraints ----------
CREATE CONSTRAINT component_name_unique IF NOT EXISTS FOR (n:`Component`) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT componentproperty_name_unique IF NOT EXISTS FOR (n:`ComponentProperty`) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT mechanism_name_unique IF NOT EXISTS FOR (n:`Mechanism`) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT mix_name_unique IF NOT EXISTS FOR (n:`Mix`) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT performanceproperty_name_unique IF NOT EXISTS FOR (n:`PerformanceProperty`) REQUIRE n.name IS UNIQUE;

// ---------- Nodes ----------
UNWIND ['Aramid fiber', 'Aramid-polyalphaolefin fiber', 'Asbestos fiber', 'Asphalt binder', 'Bagasse ash', 'Bamboo fiber', 'Basalt fiber', 'Bitumen', 'Black nanocarbon', 'Bonifiber', 'Brick waste powder', 'Brucite fiber', 'Calcium sulfate whisker fiber', 'Carbon fiber', 'Carbon nanomaterials', 'Cellulose fiber', 'Ceramic fiber', 'Coconut shell', 'Coir fiber', 'Composite granular fiber', 'Diatomite', 'Fiber', 'Forta fiber', 'Glass fiber', 'Glass fiber reinforced polymer powder', 'Glass wool fiber', 'Goat wool fiber', 'Graphite', 'High modulus agent', 'Hybrid fiber', 'Jute fiber', 'Kenaf fiber', 'Lignin fiber', 'Long-chain alkyl silane coupling agent', 'Metal particles', 'Mineral fiber', 'Nano-caco3', 'Nano-silica', 'Natural fiber', 'Nylon fiber', 'Polyacrylonitrile fiber', 'Polyamide fiber', 'Polyethylene terephthalate fiber', 'Polymer fiber', 'Polymer modified bitumen', 'Polymer-basalt fiber', 'Polymer-coated glass fiber', 'Polyolefin fiber', 'Polyolefin-aramid fiber', 'Polypropylene fiber', 'Polyvinyl alcohol fiber', 'Reclaimed asphalt pavement', 'Recycled concrete aggregate', 'Recycled fiber', 'Recycled fine aggregates powder', 'Recycled plastic carbon fiber', 'Recycled plastic fiber', 'Recycled polyethylene terephthalate fiber', 'Rejuvenator', 'Rock wool fiber', 'Rubber', 'Short-thin wheat straw pieces', 'Sisal fiber', 'Stable crumb rubber asphalt', 'Steel fiber', 'Steel slag', 'Steel wool fiber', 'Styrene-butadiene-styrene', 'Synthetic fiber', 'Synthetic fischer–tropsch wax', 'Synthetic soil fiber', 'Universal surface-active polymer', 'Warm mix asphalt additive', 'Waste glass powder', 'Wax-treated aramid fiber', 'Xylogen fiber'] AS name MERGE (n:`Component` {name:name});
UNWIND ['Axial strain', 'Complex modulus', 'Complex shear modulus', 'Compliance in extension', 'Crack resistance', 'Drain down', 'Ductility', 'Elastic property', 'Fatigue resistance', 'Fracture energy', 'Fracture resistance', 'Heat transferring performance', 'High-temperature performance', 'High-temperature rutting resistance', 'Low-temperature resistance', 'Penetration', 'Permanent strain', 'Phase angle', 'Resistance to permanent deformation', 'Rutting factor', 'Rutting resistance', 'Shear strength', 'Softening point', 'Stiffness', 'Temperature sensitivity', 'Tensile strength', 'Thermal conductivity', 'Total strain during loading period', 'Viscoelasticity', 'Viscosity', 'Yield strain energy'] AS name MERGE (n:`ComponentProperty` {name:name});
UNWIND ['Adhesion', 'Adsorption effect on fiber surface', 'Anchoring effect', 'Basalt fiber content', 'Bitumen content', 'Carbon fiber content', 'Carbon fiber length', 'Crack inhibition', 'Deformation resistance', 'Electrical conductivity', 'Fiber aspect ratio', 'Fiber bridging', 'Fiber content', 'Fiber diameter', 'Fiber dispersion', 'Fiber distribution', 'Fiber length', 'Fiber volume fraction', 'Fiber-matrix adhesion', 'High ductility', 'High durability', 'High modulus', 'High strength', 'Hybrid reinforcement', 'Microfibrillation', 'Network formation', 'Network structure', 'Polyethylene terephthalate fiber aspect ratio', 'Polyethylene terephthalate fiber volume fraction', 'Polyethylene terephthalate fiber volume ratio', 'Polymer–asphalt–aggregate interactions', 'Polyvinyl alcohol fiber length', 'Reinforcement effect', 'Shear strength', 'Stability effect', 'Stress redistribution', 'Synergistic effect', 'Synthetic fiber content', 'Tightening effect', 'Water sensitivity'] AS name MERGE (n:`Mechanism` {name:name});
UNWIND ['AC', 'FRAC'] AS name MERGE (n:`Mix` {name:name});
UNWIND ['Abrasion resistance', 'Adhesion strength', 'Aging resistance', 'Air voids', 'Bottom flexural-tensile strain', 'Cohesion', 'Compactability', 'Compressive strength', 'Crack resistance', 'Creep properties', 'Creep strain slope', 'Deflection development', 'Deformation recovery ability', 'Deformation resistance', 'Dissipated creep strain energy', 'Ductility', 'Durability', 'Dynamic modulus', 'Dynamic stability', 'Dynamic stability under Freeze–Thaw', 'Dynamic stability under UV', 'Dynamic stability under alternating high and low temperature', 'Dynamic stability under salt freezing', 'Electrical conductivity', 'Failure stiffness', 'Failure strain', 'Failure temperature', 'Fatigue resistance', 'Flexibility', 'Flexural creep', 'Flexural strength', 'Fracture energy', 'Fracture load', 'Fracture resistance', 'Fracture strength', 'Fracture toughness', 'Freeze-thaw resistance', 'Heat resistance', 'High-temperature deformation resistance', 'High-temperature dynamic modulus', 'High-temperature performance', 'High-temperature rheological properties', 'High-temperature rutting resistance', 'High-temperature stability', 'Indirect tensile stiffness modulus', 'Indirect tensile strength', 'Indirect tensile strength ratio', 'Interface properties', 'Intermediate-temperature crack resistance', 'Intermediate-temperature performance', 'Low-temperature crack resistance', 'Low-temperature dynamic modulus', 'Low-temperature flexural strength', 'Low-temperature performance', 'Low-temperature stress dissipating ability', 'Low-temperature tensile strength', 'Marshall flow value', 'Marshall quotient', 'Marshall stability', 'Maximum bending strain', 'Maximum bending stress', 'Maximum strain', 'Maximum tensile strain', 'Mechanical properties', 'Midspan deflection', 'Moisture damage resistance', 'Moisture susceptibility', 'Pavement performance', 'Permanent deformation', 'Permeability resistance', 'Phase angle', 'Reflective crack resistance', 'Resilient modulus', 'Retained marshall stability', 'Rheological properties', 'Rutting resistance', 'Self-healing ability', 'Service life', 'Shear strength', 'Stiffness modulus', 'Stress concentration', 'Stripping resistance', 'Sustainable application', 'Temperature stability', 'Tensile crack resistance', 'Tensile strain', 'Tensile strength', 'Tensile strength ratio', 'Thermal conductivity', 'Thermal crack resistance', 'Toughness', 'Viscoelastic properties', 'Viscoplastic strain', 'Viscosity', 'Voids filled with bitumen', 'Voids in mineral aggregate'] AS name MERGE (n:`PerformanceProperty`:`Property` {name:name});

// ---------- Relationships ----------
UNWIND [
  {src:'Aramid fiber', dst:'Fiber dispersion'},
  {src:'Basalt fiber', dst:'Crack inhibition'},
  {src:'Basalt fiber', dst:'Stress redistribution'},
  {src:'Carbon fiber', dst:'Stress redistribution'},
  {src:'Glass fiber', dst:'Hybrid reinforcement'},
  {src:'Polypropylene fiber', dst:'Hybrid reinforcement'},
  {src:'Rock wool fiber', dst:'Fiber distribution'},
  {src:'Rock wool fiber', dst:'Network structure'},
  {src:'Rock wool fiber', dst:'Tightening effect'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Causes`]->(b);
UNWIND [
  {src:'Asbestos fiber', dst:'Network formation'},
  {src:'Basalt fiber', dst:'Network structure'},
  {src:'Carbon fiber', dst:'Fiber bridging'},
  {src:'Lignin fiber', dst:'Network formation'},
  {src:'Polyacrylonitrile fiber', dst:'Network formation'},
  {src:'Polyethylene terephthalate fiber', dst:'Network formation'},
  {src:'Polyethylene terephthalate fiber', dst:'Network structure'},
  {src:'Polymer fiber', dst:'Network formation'},
  {src:'Synthetic fiber', dst:'Fiber bridging'},
  {src:'Synthetic fiber', dst:'Synergistic effect'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Creates`]->(b);
UNWIND [
  {src:'Basalt fiber', dst:'Axial strain'},
  {src:'Brucite fiber', dst:'Compliance in extension'},
  {src:'Brucite fiber', dst:'Ductility'},
  {src:'Brucite fiber', dst:'Temperature sensitivity'},
  {src:'Brucite fiber', dst:'Yield strain energy'},
  {src:'Cellulose fiber', dst:'Permanent strain'},
  {src:'Cellulose fiber', dst:'Phase angle'},
  {src:'Cellulose fiber', dst:'Total strain during loading period'},
  {src:'Ceramic fiber', dst:'Low-temperature resistance'},
  {src:'Fiber', dst:'Drain down'},
  {src:'Fiber', dst:'Penetration'},
  {src:'Fiber', dst:'Phase angle'},
  {src:'Lignin fiber', dst:'Fatigue resistance'},
  {src:'Mineral fiber', dst:'Permanent strain'},
  {src:'Mineral fiber', dst:'Phase angle'},
  {src:'Mineral fiber', dst:'Total strain during loading period'},
  {src:'Polyethylene terephthalate fiber', dst:'Fatigue resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Permanent strain'},
  {src:'Polyethylene terephthalate fiber', dst:'Phase angle'},
  {src:'Polyethylene terephthalate fiber', dst:'Total strain during loading period'},
  {src:'Polypropylene fiber', dst:'Ductility'},
  {src:'Polypropylene fiber', dst:'Fatigue resistance'},
  {src:'Polypropylene fiber', dst:'Penetration'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`ComponentProperty` {name: row.dst})
MERGE (a)-[:`Decreases`]->(b);
UNWIND [
  {src:'Basalt fiber', dst:'Water sensitivity'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Decreases`]->(b);
UNWIND [
  {src:'Aramid fiber', dst:'Abrasion resistance'},
  {src:'Aramid fiber', dst:'Viscoplastic strain'},
  {src:'Bamboo fiber', dst:'Air voids'},
  {src:'Basalt fiber', dst:'Dynamic modulus'},
  {src:'Basalt fiber', dst:'Failure stiffness'},
  {src:'Basalt fiber', dst:'Fracture toughness'},
  {src:'Basalt fiber', dst:'Low-temperature dynamic modulus'},
  {src:'Basalt fiber', dst:'Phase angle'},
  {src:'Basalt fiber', dst:'Stress concentration'},
  {src:'Basalt fiber', dst:'Tensile strength'},
  {src:'Bonifiber', dst:'Deflection development'},
  {src:'Carbon fiber', dst:'Marshall flow value'},
  {src:'Carbon fiber', dst:'Moisture susceptibility'},
  {src:'Cellulose fiber', dst:'Phase angle'},
  {src:'Coir fiber', dst:'Air voids'},
  {src:'Fiber', dst:'Moisture susceptibility'},
  {src:'Glass fiber', dst:'Dynamic modulus'},
  {src:'Glass fiber', dst:'Moisture susceptibility'},
  {src:'Glass fiber', dst:'Permanent deformation'},
  {src:'Glass fiber', dst:'Tensile strength'},
  {src:'Graphite', dst:'Air voids'},
  {src:'Graphite', dst:'Electrical conductivity'},
  {src:'Graphite', dst:'Low-temperature performance'},
  {src:'Graphite', dst:'Marshall stability'},
  {src:'High modulus agent', dst:'Fatigue resistance'},
  {src:'High modulus agent', dst:'Thermal crack resistance'},
  {src:'Jute fiber', dst:'Air voids'},
  {src:'Nylon fiber', dst:'Creep strain slope'},
  {src:'Polyethylene terephthalate fiber', dst:'Phase angle'},
  {src:'Polyethylene terephthalate fiber', dst:'Viscoelastic properties'},
  {src:'Polymer fiber', dst:'Tensile strength'},
  {src:'Polymer modified bitumen', dst:'Abrasion resistance'},
  {src:'Polyolefin fiber', dst:'Viscoplastic strain'},
  {src:'Polypropylene fiber', dst:'Marshall flow value'},
  {src:'Reclaimed asphalt pavement', dst:'Crack resistance'},
  {src:'Reclaimed asphalt pavement', dst:'Fatigue resistance'},
  {src:'Reclaimed asphalt pavement', dst:'Fracture energy'},
  {src:'Reclaimed asphalt pavement', dst:'Low-temperature performance'},
  {src:'Reclaimed asphalt pavement', dst:'Moisture susceptibility'},
  {src:'Reclaimed asphalt pavement', dst:'Thermal crack resistance'},
  {src:'Recycled concrete aggregate', dst:'Deformation resistance'},
  {src:'Recycled concrete aggregate', dst:'Marshall stability'},
  {src:'Recycled concrete aggregate', dst:'Stiffness modulus'},
  {src:'Rubber', dst:'Compressive strength'},
  {src:'Rubber', dst:'Voids in mineral aggregate'},
  {src:'Sisal fiber', dst:'Air voids'},
  {src:'Steel fiber', dst:'Dynamic modulus'},
  {src:'Steel fiber', dst:'Tensile strength'},
  {src:'Steel fiber', dst:'Voids in mineral aggregate'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Decreases`]->(b);
UNWIND [
  {src:'Aramid fiber', dst:'Fiber distribution'},
  {src:'Basalt fiber', dst:'Adsorption effect on fiber surface'},
  {src:'Basalt fiber', dst:'Anchoring effect'},
  {src:'Basalt fiber', dst:'Fiber bridging'},
  {src:'Basalt fiber', dst:'Reinforcement effect'},
  {src:'Basalt fiber', dst:'Stability effect'},
  {src:'Carbon nanomaterials', dst:'Adhesion'},
  {src:'Carbon nanomaterials', dst:'Electrical conductivity'},
  {src:'Fiber', dst:'Deformation resistance'},
  {src:'Fiber', dst:'Reinforcement effect'},
  {src:'Glass fiber', dst:'Reinforcement effect'},
  {src:'Polyethylene terephthalate fiber', dst:'High modulus'},
  {src:'Synthetic fiber', dst:'High ductility'},
  {src:'Synthetic fiber', dst:'High durability'},
  {src:'Synthetic fiber', dst:'High strength'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Exhibits`]->(b);
UNWIND [
  {src:'Aramid fiber', dst:'Microfibrillation'},
  {src:'Basalt fiber', dst:'Basalt fiber content'},
  {src:'Basalt fiber', dst:'Reinforcement effect'},
  {src:'Bitumen', dst:'Bitumen content'},
  {src:'Carbon fiber', dst:'Carbon fiber content'},
  {src:'Carbon fiber', dst:'Carbon fiber length'},
  {src:'Fiber', dst:'Fiber content'},
  {src:'Fiber', dst:'Fiber diameter'},
  {src:'Fiber', dst:'Fiber length'},
  {src:'Graphite', dst:'Electrical conductivity'},
  {src:'Metal particles', dst:'Electrical conductivity'},
  {src:'Nano-caco3', dst:'Adsorption effect on fiber surface'},
  {src:'Polyacrylonitrile fiber', dst:'Fiber content'},
  {src:'Polyacrylonitrile fiber', dst:'Fiber length'},
  {src:'Polyethylene terephthalate fiber', dst:'Fiber aspect ratio'},
  {src:'Polyethylene terephthalate fiber', dst:'Fiber volume fraction'},
  {src:'Polyethylene terephthalate fiber', dst:'Polyethylene terephthalate fiber aspect ratio'},
  {src:'Polyethylene terephthalate fiber', dst:'Polyethylene terephthalate fiber volume fraction'},
  {src:'Polyethylene terephthalate fiber', dst:'Polyethylene terephthalate fiber volume ratio'},
  {src:'Polyvinyl alcohol fiber', dst:'Polyvinyl alcohol fiber length'},
  {src:'Steel fiber', dst:'Adsorption effect on fiber surface'},
  {src:'Steel fiber', dst:'Electrical conductivity'},
  {src:'Synthetic fiber', dst:'Synthetic fiber content'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Has`]->(b);
UNWIND [
  {src:'Aramid fiber', dst:'Crack resistance'},
  {src:'Basalt fiber', dst:'Ductility'},
  {src:'Basalt fiber', dst:'Fatigue resistance'},
  {src:'Basalt fiber', dst:'Penetration'},
  {src:'Basalt fiber', dst:'Rutting factor'},
  {src:'Basalt fiber', dst:'Softening point'},
  {src:'Basalt fiber', dst:'Stiffness'},
  {src:'Basalt fiber', dst:'Tensile strength'},
  {src:'Brucite fiber', dst:'Viscosity'},
  {src:'Cellulose fiber', dst:'Complex shear modulus'},
  {src:'Cellulose fiber', dst:'Elastic property'},
  {src:'Cellulose fiber', dst:'Resistance to permanent deformation'},
  {src:'Cellulose fiber', dst:'Stiffness'},
  {src:'Cellulose fiber', dst:'Viscosity'},
  {src:'Ceramic fiber', dst:'Crack resistance'},
  {src:'Ceramic fiber', dst:'High-temperature performance'},
  {src:'Ceramic fiber', dst:'Rutting resistance'},
  {src:'Fiber', dst:'Complex modulus'},
  {src:'Fiber', dst:'Complex shear modulus'},
  {src:'Fiber', dst:'Elastic property'},
  {src:'Fiber', dst:'Fracture energy'},
  {src:'Fiber', dst:'Fracture resistance'},
  {src:'Fiber', dst:'High-temperature performance'},
  {src:'Fiber', dst:'High-temperature rutting resistance'},
  {src:'Fiber', dst:'Rutting resistance'},
  {src:'Fiber', dst:'Shear strength'},
  {src:'Fiber', dst:'Softening point'},
  {src:'Fiber', dst:'Tensile strength'},
  {src:'Fiber', dst:'Viscoelasticity'},
  {src:'Fiber', dst:'Viscosity'},
  {src:'Lignin fiber', dst:'Rutting resistance'},
  {src:'Mineral fiber', dst:'Complex shear modulus'},
  {src:'Mineral fiber', dst:'Elastic property'},
  {src:'Mineral fiber', dst:'Resistance to permanent deformation'},
  {src:'Mineral fiber', dst:'Stiffness'},
  {src:'Mineral fiber', dst:'Viscosity'},
  {src:'Polyethylene terephthalate fiber', dst:'Complex shear modulus'},
  {src:'Polyethylene terephthalate fiber', dst:'Elastic property'},
  {src:'Polyethylene terephthalate fiber', dst:'Resistance to permanent deformation'},
  {src:'Polyethylene terephthalate fiber', dst:'Rutting resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Stiffness'},
  {src:'Polyethylene terephthalate fiber', dst:'Viscosity'},
  {src:'Polypropylene fiber', dst:'Rutting resistance'},
  {src:'Polypropylene fiber', dst:'Softening point'},
  {src:'Polypropylene fiber', dst:'Viscosity'},
  {src:'Styrene-butadiene-styrene', dst:'Crack resistance'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`ComponentProperty` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Carbon nanomaterials', dst:'Fiber dispersion'},
  {src:'Carbon nanomaterials', dst:'Fiber-matrix adhesion'},
  {src:'Fiber', dst:'Shear strength'},
  {src:'Universal surface-active polymer', dst:'Polymer–asphalt–aggregate interactions'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Aramid fiber', dst:'Crack resistance'},
  {src:'Aramid fiber', dst:'Fatigue resistance'},
  {src:'Aramid fiber', dst:'Indirect tensile stiffness modulus'},
  {src:'Aramid fiber', dst:'Indirect tensile strength'},
  {src:'Aramid fiber', dst:'Low-temperature crack resistance'},
  {src:'Aramid fiber', dst:'Marshall stability'},
  {src:'Aramid fiber', dst:'Moisture damage resistance'},
  {src:'Aramid fiber', dst:'Resilient modulus'},
  {src:'Aramid fiber', dst:'Rutting resistance'},
  {src:'Aramid-polyalphaolefin fiber', dst:'Low-temperature performance'},
  {src:'Asbestos fiber', dst:'Fatigue resistance'},
  {src:'Asbestos fiber', dst:'Rutting resistance'},
  {src:'Asbestos fiber', dst:'Toughness'},
  {src:'Asphalt binder', dst:'Fatigue resistance'},
  {src:'Asphalt binder', dst:'High-temperature stability'},
  {src:'Asphalt binder', dst:'Marshall flow value'},
  {src:'Asphalt binder', dst:'Marshall stability'},
  {src:'Asphalt binder', dst:'Moisture damage resistance'},
  {src:'Asphalt binder', dst:'Rutting resistance'},
  {src:'Asphalt binder', dst:'Self-healing ability'},
  {src:'Asphalt binder', dst:'Sustainable application'},
  {src:'Asphalt binder', dst:'Thermal conductivity'},
  {src:'Bagasse ash', dst:'Rutting resistance'},
  {src:'Bamboo fiber', dst:'Fatigue resistance'},
  {src:'Bamboo fiber', dst:'Flexural strength'},
  {src:'Bamboo fiber', dst:'High-temperature stability'},
  {src:'Bamboo fiber', dst:'Low-temperature crack resistance'},
  {src:'Bamboo fiber', dst:'Maximum tensile strain'},
  {src:'Bamboo fiber', dst:'Moisture susceptibility'},
  {src:'Bamboo fiber', dst:'Retained marshall stability'},
  {src:'Basalt fiber', dst:'Abrasion resistance'},
  {src:'Basalt fiber', dst:'Adhesion strength'},
  {src:'Basalt fiber', dst:'Cohesion'},
  {src:'Basalt fiber', dst:'Crack resistance'},
  {src:'Basalt fiber', dst:'Deformation resistance'},
  {src:'Basalt fiber', dst:'Dissipated creep strain energy'},
  {src:'Basalt fiber', dst:'Ductility'},
  {src:'Basalt fiber', dst:'Durability'},
  {src:'Basalt fiber', dst:'Dynamic modulus'},
  {src:'Basalt fiber', dst:'Dynamic stability'},
  {src:'Basalt fiber', dst:'Dynamic stability under Freeze–Thaw'},
  {src:'Basalt fiber', dst:'Dynamic stability under UV'},
  {src:'Basalt fiber', dst:'Dynamic stability under alternating high and low temperature'},
  {src:'Basalt fiber', dst:'Dynamic stability under salt freezing'},
  {src:'Basalt fiber', dst:'Failure stiffness'},
  {src:'Basalt fiber', dst:'Failure strain'},
  {src:'Basalt fiber', dst:'Fatigue resistance'},
  {src:'Basalt fiber', dst:'Fracture energy'},
  {src:'Basalt fiber', dst:'Fracture resistance'},
  {src:'Basalt fiber', dst:'Fracture strength'},
  {src:'Basalt fiber', dst:'Fracture toughness'},
  {src:'Basalt fiber', dst:'Heat resistance'},
  {src:'Basalt fiber', dst:'High-temperature deformation resistance'},
  {src:'Basalt fiber', dst:'High-temperature dynamic modulus'},
  {src:'Basalt fiber', dst:'High-temperature performance'},
  {src:'Basalt fiber', dst:'High-temperature rheological properties'},
  {src:'Basalt fiber', dst:'High-temperature rutting resistance'},
  {src:'Basalt fiber', dst:'High-temperature stability'},
  {src:'Basalt fiber', dst:'Indirect tensile strength'},
  {src:'Basalt fiber', dst:'Interface properties'},
  {src:'Basalt fiber', dst:'Intermediate-temperature crack resistance'},
  {src:'Basalt fiber', dst:'Low-temperature crack resistance'},
  {src:'Basalt fiber', dst:'Low-temperature flexural strength'},
  {src:'Basalt fiber', dst:'Low-temperature performance'},
  {src:'Basalt fiber', dst:'Low-temperature stress dissipating ability'},
  {src:'Basalt fiber', dst:'Low-temperature tensile strength'},
  {src:'Basalt fiber', dst:'Marshall stability'},
  {src:'Basalt fiber', dst:'Maximum bending strain'},
  {src:'Basalt fiber', dst:'Mechanical properties'},
  {src:'Basalt fiber', dst:'Moisture susceptibility'},
  {src:'Basalt fiber', dst:'Pavement performance'},
  {src:'Basalt fiber', dst:'Resilient modulus'},
  {src:'Basalt fiber', dst:'Rheological properties'},
  {src:'Basalt fiber', dst:'Rutting resistance'},
  {src:'Basalt fiber', dst:'Service life'},
  {src:'Basalt fiber', dst:'Shear strength'},
  {src:'Basalt fiber', dst:'Stripping resistance'},
  {src:'Basalt fiber', dst:'Temperature stability'},
  {src:'Basalt fiber', dst:'Tensile strength'},
  {src:'Basalt fiber', dst:'Tensile strength ratio'},
  {src:'Basalt fiber', dst:'Viscoelastic properties'},
  {src:'Black nanocarbon', dst:'Marshall flow value'},
  {src:'Black nanocarbon', dst:'Marshall stability'},
  {src:'Bonifiber', dst:'Crack resistance'},
  {src:'Bonifiber', dst:'Interface properties'},
  {src:'Bonifiber', dst:'Pavement performance'},
  {src:'Bonifiber', dst:'Toughness'},
  {src:'Brick waste powder', dst:'Moisture susceptibility'},
  {src:'Brucite fiber', dst:'Crack resistance'},
  {src:'Brucite fiber', dst:'High-temperature stability'},
  {src:'Brucite fiber', dst:'Low-temperature crack resistance'},
  {src:'Brucite fiber', dst:'Maximum bending strain'},
  {src:'Brucite fiber', dst:'Maximum bending stress'},
  {src:'Brucite fiber', dst:'Moisture susceptibility'},
  {src:'Calcium sulfate whisker fiber', dst:'High-temperature stability'},
  {src:'Calcium sulfate whisker fiber', dst:'Low-temperature crack resistance'},
  {src:'Calcium sulfate whisker fiber', dst:'Moisture susceptibility'},
  {src:'Carbon fiber', dst:'Crack resistance'},
  {src:'Carbon fiber', dst:'Dynamic stability'},
  {src:'Carbon fiber', dst:'Electrical conductivity'},
  {src:'Carbon fiber', dst:'Fracture resistance'},
  {src:'Carbon fiber', dst:'Fracture toughness'},
  {src:'Carbon fiber', dst:'High-temperature performance'},
  {src:'Carbon fiber', dst:'High-temperature rutting resistance'},
  {src:'Carbon fiber', dst:'Indirect tensile strength ratio'},
  {src:'Carbon fiber', dst:'Marshall stability'},
  {src:'Carbon fiber', dst:'Moisture susceptibility'},
  {src:'Carbon fiber', dst:'Pavement performance'},
  {src:'Carbon fiber', dst:'Retained marshall stability'},
  {src:'Carbon fiber', dst:'Rutting resistance'},
  {src:'Cellulose fiber', dst:'Dynamic modulus'},
  {src:'Cellulose fiber', dst:'Fatigue resistance'},
  {src:'Cellulose fiber', dst:'High-temperature deformation resistance'},
  {src:'Cellulose fiber', dst:'Viscoelastic properties'},
  {src:'Ceramic fiber', dst:'Fatigue resistance'},
  {src:'Ceramic fiber', dst:'Rutting resistance'},
  {src:'Composite granular fiber', dst:'High-temperature rutting resistance'},
  {src:'Composite granular fiber', dst:'Low-temperature crack resistance'},
  {src:'Diatomite', dst:'Fatigue resistance'},
  {src:'Diatomite', dst:'Low-temperature performance'},
  {src:'Diatomite', dst:'Tensile strength'},
  {src:'Fiber', dst:'Crack resistance'},
  {src:'Fiber', dst:'Deformation resistance'},
  {src:'Fiber', dst:'Failure temperature'},
  {src:'Fiber', dst:'Fatigue resistance'},
  {src:'Fiber', dst:'Fracture resistance'},
  {src:'Fiber', dst:'Fracture strength'},
  {src:'Fiber', dst:'Indirect tensile strength'},
  {src:'Fiber', dst:'Rutting resistance'},
  {src:'Fiber', dst:'Stiffness modulus'},
  {src:'Fiber', dst:'Tensile strength ratio'},
  {src:'Forta fiber', dst:'Crack resistance'},
  {src:'Glass fiber', dst:'Abrasion resistance'},
  {src:'Glass fiber', dst:'Compactability'},
  {src:'Glass fiber', dst:'Crack resistance'},
  {src:'Glass fiber', dst:'Deformation resistance'},
  {src:'Glass fiber', dst:'Dissipated creep strain energy'},
  {src:'Glass fiber', dst:'Ductility'},
  {src:'Glass fiber', dst:'Dynamic modulus'},
  {src:'Glass fiber', dst:'Failure strain'},
  {src:'Glass fiber', dst:'Fatigue resistance'},
  {src:'Glass fiber', dst:'Fracture energy'},
  {src:'Glass fiber', dst:'Fracture resistance'},
  {src:'Glass fiber', dst:'Indirect tensile strength'},
  {src:'Glass fiber', dst:'Low-temperature crack resistance'},
  {src:'Glass fiber', dst:'Low-temperature performance'},
  {src:'Glass fiber', dst:'Marshall stability'},
  {src:'Glass fiber', dst:'Moisture damage resistance'},
  {src:'Glass fiber', dst:'Moisture susceptibility'},
  {src:'Glass fiber', dst:'Rutting resistance'},
  {src:'Glass fiber', dst:'Stiffness modulus'},
  {src:'Glass fiber', dst:'Toughness'},
  {src:'Glass fiber reinforced polymer powder', dst:'Fatigue resistance'},
  {src:'Glass fiber reinforced polymer powder', dst:'High-temperature performance'},
  {src:'Glass fiber reinforced polymer powder', dst:'Intermediate-temperature performance'},
  {src:'Glass fiber reinforced polymer powder', dst:'Rutting resistance'},
  {src:'Glass wool fiber', dst:'Moisture susceptibility'},
  {src:'Glass wool fiber', dst:'Rutting resistance'},
  {src:'Goat wool fiber', dst:'Fracture strength'},
  {src:'Graphite', dst:'Deformation resistance'},
  {src:'Graphite', dst:'Pavement performance'},
  {src:'High modulus agent', dst:'Dynamic modulus'},
  {src:'High modulus agent', dst:'Moisture susceptibility'},
  {src:'High modulus agent', dst:'Rutting resistance'},
  {src:'Hybrid fiber', dst:'Fatigue resistance'},
  {src:'Hybrid fiber', dst:'High-temperature deformation resistance'},
  {src:'Hybrid fiber', dst:'Moisture susceptibility'},
  {src:'Jute fiber', dst:'Crack resistance'},
  {src:'Jute fiber', dst:'Fracture resistance'},
  {src:'Kenaf fiber', dst:'Fracture resistance'},
  {src:'Kenaf fiber', dst:'Fracture strength'},
  {src:'Lignin fiber', dst:'Crack resistance'},
  {src:'Lignin fiber', dst:'Fatigue resistance'},
  {src:'Lignin fiber', dst:'Flexural strength'},
  {src:'Lignin fiber', dst:'High-temperature stability'},
  {src:'Lignin fiber', dst:'Low-temperature performance'},
  {src:'Lignin fiber', dst:'Moisture susceptibility'},
  {src:'Lignin fiber', dst:'Retained marshall stability'},
  {src:'Lignin fiber', dst:'Rutting resistance'},
  {src:'Lignin fiber', dst:'Toughness'},
  {src:'Long-chain alkyl silane coupling agent', dst:'Moisture susceptibility'},
  {src:'Long-chain alkyl silane coupling agent', dst:'Rutting resistance'},
  {src:'Nano-caco3', dst:'Fracture energy'},
  {src:'Nano-silica', dst:'Abrasion resistance'},
  {src:'Nano-silica', dst:'Crack resistance'},
  {src:'Nano-silica', dst:'Rutting resistance'},
  {src:'Natural fiber', dst:'Abrasion resistance'},
  {src:'Natural fiber', dst:'Deformation resistance'},
  {src:'Natural fiber', dst:'Indirect tensile strength'},
  {src:'Natural fiber', dst:'Rutting resistance'},
  {src:'Nylon fiber', dst:'Fatigue resistance'},
  {src:'Nylon fiber', dst:'Fracture energy'},
  {src:'Nylon fiber', dst:'Indirect tensile strength'},
  {src:'Nylon fiber', dst:'Marshall flow value'},
  {src:'Nylon fiber', dst:'Marshall quotient'},
  {src:'Nylon fiber', dst:'Marshall stability'},
  {src:'Nylon fiber', dst:'Rutting resistance'},
  {src:'Polyacrylonitrile fiber', dst:'Deformation resistance'},
  {src:'Polyacrylonitrile fiber', dst:'Fatigue resistance'},
  {src:'Polyacrylonitrile fiber', dst:'Flexural strength'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Polyacrylonitrile fiber', dst:'Maximum strain'},
  {src:'Polyacrylonitrile fiber', dst:'Rutting resistance'},
  {src:'Polyacrylonitrile fiber', dst:'Toughness'},
  {src:'Polyamide fiber', dst:'Rutting resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Aging resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Deformation resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Dynamic modulus'},
  {src:'Polyethylene terephthalate fiber', dst:'Failure strain'},
  {src:'Polyethylene terephthalate fiber', dst:'Fatigue resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Flexibility'},
  {src:'Polyethylene terephthalate fiber', dst:'Flexural strength'},
  {src:'Polyethylene terephthalate fiber', dst:'High-temperature deformation resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'High-temperature stability'},
  {src:'Polyethylene terephthalate fiber', dst:'Low-temperature crack resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Low-temperature performance'},
  {src:'Polyethylene terephthalate fiber', dst:'Marshall flow value'},
  {src:'Polyethylene terephthalate fiber', dst:'Marshall stability'},
  {src:'Polyethylene terephthalate fiber', dst:'Maximum strain'},
  {src:'Polyethylene terephthalate fiber', dst:'Moisture susceptibility'},
  {src:'Polyethylene terephthalate fiber', dst:'Pavement performance'},
  {src:'Polyethylene terephthalate fiber', dst:'Rutting resistance'},
  {src:'Polyethylene terephthalate fiber', dst:'Stiffness modulus'},
  {src:'Polyethylene terephthalate fiber', dst:'Tensile strength'},
  {src:'Polyethylene terephthalate fiber', dst:'Toughness'},
  {src:'Polyethylene terephthalate fiber', dst:'Viscoelastic properties'},
  {src:'Polymer fiber', dst:'Fatigue resistance'},
  {src:'Polymer fiber', dst:'High-temperature stability'},
  {src:'Polymer fiber', dst:'Low-temperature crack resistance'},
  {src:'Polymer fiber', dst:'Marshall stability'},
  {src:'Polymer fiber', dst:'Moisture susceptibility'},
  {src:'Polymer fiber', dst:'Reflective crack resistance'},
  {src:'Polymer fiber', dst:'Rutting resistance'},
  {src:'Polymer fiber', dst:'Stiffness modulus'},
  {src:'Polymer fiber', dst:'Tensile strain'},
  {src:'Polymer fiber', dst:'Viscoelastic properties'},
  {src:'Polymer-basalt fiber', dst:'Compactability'},
  {src:'Polymer-basalt fiber', dst:'Deformation resistance'},
  {src:'Polymer-basalt fiber', dst:'Freeze-thaw resistance'},
  {src:'Polymer-basalt fiber', dst:'Moisture susceptibility'},
  {src:'Polymer-coated glass fiber', dst:'Rutting resistance'},
  {src:'Polyolefin fiber', dst:'Crack resistance'},
  {src:'Polyolefin fiber', dst:'Fatigue resistance'},
  {src:'Polyolefin fiber', dst:'Indirect tensile stiffness modulus'},
  {src:'Polyolefin fiber', dst:'Indirect tensile strength'},
  {src:'Polyolefin fiber', dst:'Marshall stability'},
  {src:'Polyolefin fiber', dst:'Resilient modulus'},
  {src:'Polyolefin fiber', dst:'Rutting resistance'},
  {src:'Polyolefin-aramid fiber', dst:'Fracture toughness'},
  {src:'Polypropylene fiber', dst:'Air voids'},
  {src:'Polypropylene fiber', dst:'Crack resistance'},
  {src:'Polypropylene fiber', dst:'Creep properties'},
  {src:'Polypropylene fiber', dst:'Failure strain'},
  {src:'Polypropylene fiber', dst:'Fatigue resistance'},
  {src:'Polypropylene fiber', dst:'High-temperature deformation resistance'},
  {src:'Polypropylene fiber', dst:'Low-temperature crack resistance'},
  {src:'Polypropylene fiber', dst:'Low-temperature performance'},
  {src:'Polypropylene fiber', dst:'Marshall stability'},
  {src:'Polypropylene fiber', dst:'Moisture susceptibility'},
  {src:'Polypropylene fiber', dst:'Rutting resistance'},
  {src:'Polyvinyl alcohol fiber', dst:'Crack resistance'},
  {src:'Polyvinyl alcohol fiber', dst:'Flexibility'},
  {src:'Polyvinyl alcohol fiber', dst:'Fracture energy'},
  {src:'Polyvinyl alcohol fiber', dst:'Stiffness modulus'},
  {src:'Reclaimed asphalt pavement', dst:'Dynamic modulus'},
  {src:'Reclaimed asphalt pavement', dst:'High-temperature stability'},
  {src:'Reclaimed asphalt pavement', dst:'Indirect tensile strength'},
  {src:'Reclaimed asphalt pavement', dst:'Moisture susceptibility'},
  {src:'Reclaimed asphalt pavement', dst:'Rutting resistance'},
  {src:'Reclaimed asphalt pavement', dst:'Stiffness modulus'},
  {src:'Recycled concrete aggregate', dst:'High-temperature stability'},
  {src:'Recycled concrete aggregate', dst:'Low-temperature crack resistance'},
  {src:'Recycled fiber', dst:'Durability'},
  {src:'Recycled fiber', dst:'Dynamic modulus'},
  {src:'Recycled fiber', dst:'Fatigue resistance'},
  {src:'Recycled fiber', dst:'Moisture susceptibility'},
  {src:'Recycled fine aggregates powder', dst:'Fatigue resistance'},
  {src:'Recycled fine aggregates powder', dst:'Moisture susceptibility'},
  {src:'Recycled plastic carbon fiber', dst:'Moisture damage resistance'},
  {src:'Recycled plastic carbon fiber', dst:'Rutting resistance'},
  {src:'Recycled plastic fiber', dst:'Fatigue resistance'},
  {src:'Recycled plastic fiber', dst:'Fracture energy'},
  {src:'Recycled plastic fiber', dst:'Toughness'},
  {src:'Recycled polyethylene terephthalate fiber', dst:'Fatigue resistance'},
  {src:'Recycled polyethylene terephthalate fiber', dst:'Resilient modulus'},
  {src:'Recycled polyethylene terephthalate fiber', dst:'Rutting resistance'},
  {src:'Rejuvenator', dst:'Low-temperature performance'},
  {src:'Rock wool fiber', dst:'Marshall flow value'},
  {src:'Rock wool fiber', dst:'Marshall stability'},
  {src:'Rock wool fiber', dst:'Moisture susceptibility'},
  {src:'Rock wool fiber', dst:'Tensile strength ratio'},
  {src:'Rubber', dst:'Aging resistance'},
  {src:'Rubber', dst:'Crack resistance'},
  {src:'Rubber', dst:'Deformation recovery ability'},
  {src:'Rubber', dst:'Deformation resistance'},
  {src:'Rubber', dst:'Fracture strength'},
  {src:'Rubber', dst:'High-temperature stability'},
  {src:'Rubber', dst:'Low-temperature crack resistance'},
  {src:'Rubber', dst:'Low-temperature performance'},
  {src:'Rubber', dst:'Moisture susceptibility'},
  {src:'Rubber', dst:'Permeability resistance'},
  {src:'Rubber', dst:'Reflective crack resistance'},
  {src:'Rubber', dst:'Stiffness modulus'},
  {src:'Short-thin wheat straw pieces', dst:'Dynamic stability'},
  {src:'Short-thin wheat straw pieces', dst:'Flexural strength'},
  {src:'Short-thin wheat straw pieces', dst:'Fracture toughness'},
  {src:'Short-thin wheat straw pieces', dst:'High-temperature stability'},
  {src:'Short-thin wheat straw pieces', dst:'Low-temperature crack resistance'},
  {src:'Short-thin wheat straw pieces', dst:'Moisture susceptibility'},
  {src:'Short-thin wheat straw pieces', dst:'Rutting resistance'},
  {src:'Sisal fiber', dst:'Deformation resistance'},
  {src:'Sisal fiber', dst:'Marshall flow value'},
  {src:'Sisal fiber', dst:'Moisture damage resistance'},
  {src:'Sisal fiber', dst:'Tensile strength'},
  {src:'Stable crumb rubber asphalt', dst:'Low-temperature performance'},
  {src:'Steel fiber', dst:'Air voids'},
  {src:'Steel fiber', dst:'Compactability'},
  {src:'Steel fiber', dst:'Crack resistance'},
  {src:'Steel fiber', dst:'Deformation resistance'},
  {src:'Steel fiber', dst:'Dissipated creep strain energy'},
  {src:'Steel fiber', dst:'Ductility'},
  {src:'Steel fiber', dst:'Failure strain'},
  {src:'Steel fiber', dst:'Flexural strength'},
  {src:'Steel fiber', dst:'Fracture energy'},
  {src:'Steel fiber', dst:'Fracture resistance'},
  {src:'Steel fiber', dst:'Freeze-thaw resistance'},
  {src:'Steel fiber', dst:'High-temperature rutting resistance'},
  {src:'Steel fiber', dst:'Indirect tensile strength'},
  {src:'Steel fiber', dst:'Low-temperature crack resistance'},
  {src:'Steel fiber', dst:'Low-temperature performance'},
  {src:'Steel fiber', dst:'Marshall flow value'},
  {src:'Steel fiber', dst:'Marshall stability'},
  {src:'Steel fiber', dst:'Permeability resistance'},
  {src:'Steel fiber', dst:'Rutting resistance'},
  {src:'Steel fiber', dst:'Self-healing ability'},
  {src:'Steel fiber', dst:'Stiffness modulus'},
  {src:'Steel fiber', dst:'Tensile crack resistance'},
  {src:'Steel fiber', dst:'Toughness'},
  {src:'Steel slag', dst:'Moisture susceptibility'},
  {src:'Steel wool fiber', dst:'Crack resistance'},
  {src:'Steel wool fiber', dst:'Stiffness modulus'},
  {src:'Synthetic fiber', dst:'Crack resistance'},
  {src:'Synthetic fiber', dst:'Deformation resistance'},
  {src:'Synthetic fiber', dst:'Fatigue resistance'},
  {src:'Synthetic fiber', dst:'Fracture resistance'},
  {src:'Synthetic fiber', dst:'Moisture susceptibility'},
  {src:'Synthetic fiber', dst:'Resilient modulus'},
  {src:'Synthetic fiber', dst:'Rutting resistance'},
  {src:'Synthetic fiber', dst:'Stiffness modulus'},
  {src:'Synthetic fiber', dst:'Tensile strength'},
  {src:'Synthetic fiber', dst:'Thermal crack resistance'},
  {src:'Synthetic fischer–tropsch wax', dst:'Compactability'},
  {src:'Synthetic fischer–tropsch wax', dst:'Deformation resistance'},
  {src:'Synthetic fischer–tropsch wax', dst:'Freeze-thaw resistance'},
  {src:'Synthetic fischer–tropsch wax', dst:'Moisture susceptibility'},
  {src:'Synthetic soil fiber', dst:'Fatigue resistance'},
  {src:'Synthetic soil fiber', dst:'Rutting resistance'},
  {src:'Synthetic soil fiber', dst:'Thermal crack resistance'},
  {src:'Warm mix asphalt additive', dst:'Compactability'},
  {src:'Waste glass powder', dst:'Fatigue resistance'},
  {src:'Waste glass powder', dst:'Marshall stability'},
  {src:'Waste glass powder', dst:'Rutting resistance'},
  {src:'Wax-treated aramid fiber', dst:'Crack resistance'},
  {src:'Xylogen fiber', dst:'Pavement performance'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Coconut shell', dst:'Air voids'},
  {src:'Recycled polyethylene terephthalate fiber', dst:'Stiffness modulus'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Increases_initially_and_then_decreases`]->(b);
UNWIND [
  {src:'Glass fiber', dst:'Fiber-matrix adhesion'}
] AS row
MATCH (a:`Component` {name: row.src})
MATCH (b:`Mechanism` {name: row.dst})
MERGE (a)-[:`Positive`]->(b);
UNWIND [
  {src:'Axial strain', dst:'Asphalt binder'},
  {src:'Complex modulus', dst:'Asphalt binder'},
  {src:'Complex shear modulus', dst:'Asphalt binder'},
  {src:'Compliance in extension', dst:'Asphalt binder'},
  {src:'Crack resistance', dst:'Asphalt binder'},
  {src:'Drain down', dst:'Asphalt binder'},
  {src:'Ductility', dst:'Asphalt binder'},
  {src:'Elastic property', dst:'Asphalt binder'},
  {src:'Fatigue resistance', dst:'Asphalt binder'},
  {src:'Fracture energy', dst:'Asphalt binder'},
  {src:'Fracture resistance', dst:'Asphalt binder'},
  {src:'Heat transferring performance', dst:'Asphalt binder'},
  {src:'High-temperature performance', dst:'Asphalt binder'},
  {src:'High-temperature rutting resistance', dst:'Asphalt binder'},
  {src:'Low-temperature resistance', dst:'Asphalt binder'},
  {src:'Penetration', dst:'Asphalt binder'},
  {src:'Permanent strain', dst:'Asphalt binder'},
  {src:'Phase angle', dst:'Asphalt binder'},
  {src:'Resistance to permanent deformation', dst:'Asphalt binder'},
  {src:'Rutting factor', dst:'Asphalt binder'},
  {src:'Rutting resistance', dst:'Asphalt binder'},
  {src:'Shear strength', dst:'Asphalt binder'},
  {src:'Softening point', dst:'Asphalt binder'},
  {src:'Stiffness', dst:'Asphalt binder'},
  {src:'Temperature sensitivity', dst:'Asphalt binder'},
  {src:'Tensile strength', dst:'Asphalt binder'},
  {src:'Thermal conductivity', dst:'Asphalt binder'},
  {src:'Total strain during loading period', dst:'Asphalt binder'},
  {src:'Viscoelasticity', dst:'Asphalt binder'},
  {src:'Viscosity', dst:'Asphalt binder'},
  {src:'Yield strain energy', dst:'Asphalt binder'}
] AS row
MATCH (a:`ComponentProperty` {name: row.src})
MATCH (b:`Component` {name: row.dst})
MERGE (a)-[:`Property_of`]->(b);
UNWIND [
  {src:'Hybrid reinforcement', dst:'Marshall flow value'},
  {src:'Reinforcement effect', dst:'Fracture energy'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Decreases`]->(b);
UNWIND [
  {src:'Adhesion', dst:'Heat transferring performance'},
  {src:'Adsorption effect on fiber surface', dst:'Thermal conductivity'},
  {src:'Electrical conductivity', dst:'Heat transferring performance'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`ComponentProperty` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Adsorption effect on fiber surface', dst:'Crack resistance'},
  {src:'Anchoring effect', dst:'Crack resistance'},
  {src:'Carbon fiber length', dst:'Electrical conductivity'},
  {src:'Crack inhibition', dst:'Crack resistance'},
  {src:'Crack inhibition', dst:'Toughness'},
  {src:'Deformation resistance', dst:'Fatigue resistance'},
  {src:'Electrical conductivity', dst:'Durability'},
  {src:'Electrical conductivity', dst:'Electrical conductivity'},
  {src:'Electrical conductivity', dst:'Thermal conductivity'},
  {src:'Fiber bridging', dst:'Crack resistance'},
  {src:'Fiber bridging', dst:'Fracture resistance'},
  {src:'Fiber dispersion', dst:'Fatigue resistance'},
  {src:'Fiber dispersion', dst:'Thermal conductivity'},
  {src:'Fiber distribution', dst:'Marshall flow value'},
  {src:'Fiber distribution', dst:'Marshall stability'},
  {src:'Fiber distribution', dst:'Moisture susceptibility'},
  {src:'Fiber distribution', dst:'Rutting resistance'},
  {src:'Fiber-matrix adhesion', dst:'Mechanical properties'},
  {src:'Fiber-matrix adhesion', dst:'Thermal conductivity'},
  {src:'High ductility', dst:'Mechanical properties'},
  {src:'High durability', dst:'Mechanical properties'},
  {src:'High modulus', dst:'Reflective crack resistance'},
  {src:'High modulus', dst:'Service life'},
  {src:'High strength', dst:'Mechanical properties'},
  {src:'Hybrid reinforcement', dst:'Marshall stability'},
  {src:'Microfibrillation', dst:'Rutting resistance'},
  {src:'Network formation', dst:'Fatigue resistance'},
  {src:'Network formation', dst:'Indirect tensile strength'},
  {src:'Network formation', dst:'Rutting resistance'},
  {src:'Network structure', dst:'Marshall flow value'},
  {src:'Network structure', dst:'Marshall stability'},
  {src:'Network structure', dst:'Moisture susceptibility'},
  {src:'Network structure', dst:'Rheological properties'},
  {src:'Network structure', dst:'Tensile strength'},
  {src:'Network structure', dst:'Toughness'},
  {src:'Polymer–asphalt–aggregate interactions', dst:'Fatigue resistance'},
  {src:'Polymer–asphalt–aggregate interactions', dst:'Permeability resistance'},
  {src:'Reinforcement effect', dst:'Crack resistance'},
  {src:'Reinforcement effect', dst:'Fatigue resistance'},
  {src:'Reinforcement effect', dst:'Fracture load'},
  {src:'Reinforcement effect', dst:'Fracture toughness'},
  {src:'Reinforcement effect', dst:'Toughness'},
  {src:'Shear strength', dst:'Crack resistance'},
  {src:'Shear strength', dst:'Rutting resistance'},
  {src:'Stability effect', dst:'Crack resistance'},
  {src:'Stress redistribution', dst:'Crack resistance'},
  {src:'Stress redistribution', dst:'Fracture resistance'},
  {src:'Stress redistribution', dst:'Toughness'},
  {src:'Synergistic effect', dst:'Fracture strength'},
  {src:'Tightening effect', dst:'Marshall flow value'},
  {src:'Tightening effect', dst:'Marshall stability'},
  {src:'Tightening effect', dst:'Moisture susceptibility'},
  {src:'Water sensitivity', dst:'Moisture damage resistance'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Increases`]->(b);
UNWIND [
  {src:'Carbon fiber content', dst:'Fracture energy'},
  {src:'Carbon fiber content', dst:'Toughness'},
  {src:'Carbon fiber length', dst:'Fracture energy'},
  {src:'Carbon fiber length', dst:'Toughness'},
  {src:'Fiber aspect ratio', dst:'Flexural creep'},
  {src:'Fiber volume fraction', dst:'Flexural creep'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Increases_initially_and_then_decreases`]->(b);
UNWIND [
  {src:'Basalt fiber content', dst:'Phase angle'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Initially_negative_but_subsequently_positive`]->(b);
UNWIND [
  {src:'Basalt fiber content', dst:'High-temperature dynamic modulus'},
  {src:'Fiber content', dst:'Fatigue resistance'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Initially_positive_but_subsequently_negative`]->(b);
UNWIND [
  {src:'Basalt fiber content', dst:'Low-temperature dynamic modulus'},
  {src:'Bitumen content', dst:'Air voids'},
  {src:'Bitumen content', dst:'Voids in mineral aggregate'},
  {src:'Fiber diameter', dst:'Viscosity'},
  {src:'Fiber length', dst:'Viscosity'},
  {src:'Polyethylene terephthalate fiber aspect ratio', dst:'Bottom flexural-tensile strain'},
  {src:'Polyethylene terephthalate fiber aspect ratio', dst:'Flexural creep'},
  {src:'Polyethylene terephthalate fiber aspect ratio', dst:'Midspan deflection'},
  {src:'Polyethylene terephthalate fiber volume fraction', dst:'Flexural creep'},
  {src:'Polyethylene terephthalate fiber volume ratio', dst:'Bottom flexural-tensile strain'},
  {src:'Polyethylene terephthalate fiber volume ratio', dst:'Midspan deflection'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Negative`]->(b);
UNWIND [
  {src:'Basalt fiber content', dst:'Creep properties'},
  {src:'Bitumen content', dst:'Voids filled with bitumen'},
  {src:'Fiber content', dst:'Deformation resistance'},
  {src:'Fiber content', dst:'Fracture energy'},
  {src:'Fiber content', dst:'High-temperature stability'},
  {src:'Fiber content', dst:'Low-temperature crack resistance'},
  {src:'Fiber content', dst:'Low-temperature performance'},
  {src:'Fiber content', dst:'Rutting resistance'},
  {src:'Fiber content', dst:'Service life'},
  {src:'Fiber content', dst:'Stiffness modulus'},
  {src:'Fiber content', dst:'Tensile strength'},
  {src:'Fiber length', dst:'Service life'},
  {src:'Polyvinyl alcohol fiber length', dst:'Indirect tensile strength'},
  {src:'Polyvinyl alcohol fiber length', dst:'Toughness'},
  {src:'Synthetic fiber content', dst:'Fracture toughness'}
] AS row
MATCH (a:`Mechanism` {name: row.src})
MATCH (b:`PerformanceProperty` {name: row.dst})
MERGE (a)-[:`Positive`]->(b);
UNWIND [
  {src:'Abrasion resistance', dst:'FRAC'},
  {src:'Adhesion strength', dst:'FRAC'},
  {src:'Aging resistance', dst:'FRAC'},
  {src:'Air voids', dst:'AC'},
  {src:'Air voids', dst:'FRAC'},
  {src:'Bottom flexural-tensile strain', dst:'FRAC'},
  {src:'Cohesion', dst:'FRAC'},
  {src:'Compactability', dst:'FRAC'},
  {src:'Compressive strength', dst:'FRAC'},
  {src:'Crack resistance', dst:'AC'},
  {src:'Crack resistance', dst:'FRAC'},
  {src:'Creep properties', dst:'FRAC'},
  {src:'Creep strain slope', dst:'FRAC'},
  {src:'Deflection development', dst:'FRAC'},
  {src:'Deformation recovery ability', dst:'FRAC'},
  {src:'Deformation resistance', dst:'AC'},
  {src:'Deformation resistance', dst:'FRAC'},
  {src:'Dissipated creep strain energy', dst:'FRAC'},
  {src:'Ductility', dst:'FRAC'},
  {src:'Durability', dst:'AC'},
  {src:'Durability', dst:'FRAC'},
  {src:'Dynamic modulus', dst:'AC'},
  {src:'Dynamic modulus', dst:'FRAC'},
  {src:'Dynamic stability', dst:'FRAC'},
  {src:'Dynamic stability under Freeze–Thaw', dst:'FRAC'},
  {src:'Dynamic stability under UV', dst:'FRAC'},
  {src:'Dynamic stability under alternating high and low temperature', dst:'FRAC'},
  {src:'Dynamic stability under salt freezing', dst:'FRAC'},
  {src:'Electrical conductivity', dst:'AC'},
  {src:'Electrical conductivity', dst:'FRAC'},
  {src:'Failure stiffness', dst:'FRAC'},
  {src:'Failure strain', dst:'FRAC'},
  {src:'Failure temperature', dst:'FRAC'},
  {src:'Fatigue resistance', dst:'AC'},
  {src:'Fatigue resistance', dst:'FRAC'},
  {src:'Flexibility', dst:'FRAC'},
  {src:'Flexural creep', dst:'FRAC'},
  {src:'Flexural strength', dst:'FRAC'},
  {src:'Fracture energy', dst:'AC'},
  {src:'Fracture energy', dst:'FRAC'},
  {src:'Fracture load', dst:'FRAC'},
  {src:'Fracture resistance', dst:'FRAC'},
  {src:'Fracture strength', dst:'FRAC'},
  {src:'Fracture toughness', dst:'FRAC'},
  {src:'Freeze-thaw resistance', dst:'FRAC'},
  {src:'Heat resistance', dst:'FRAC'},
  {src:'High-temperature deformation resistance', dst:'FRAC'},
  {src:'High-temperature dynamic modulus', dst:'FRAC'},
  {src:'High-temperature performance', dst:'FRAC'},
  {src:'High-temperature rheological properties', dst:'FRAC'},
  {src:'High-temperature rutting resistance', dst:'FRAC'},
  {src:'High-temperature stability', dst:'AC'},
  {src:'High-temperature stability', dst:'FRAC'},
  {src:'Indirect tensile stiffness modulus', dst:'FRAC'},
  {src:'Indirect tensile strength', dst:'FRAC'},
  {src:'Indirect tensile strength ratio', dst:'FRAC'},
  {src:'Interface properties', dst:'FRAC'},
  {src:'Intermediate-temperature crack resistance', dst:'FRAC'},
  {src:'Intermediate-temperature performance', dst:'FRAC'},
  {src:'Low-temperature crack resistance', dst:'AC'},
  {src:'Low-temperature crack resistance', dst:'FRAC'},
  {src:'Low-temperature dynamic modulus', dst:'FRAC'},
  {src:'Low-temperature flexural strength', dst:'FRAC'},
  {src:'Low-temperature performance', dst:'AC'},
  {src:'Low-temperature performance', dst:'FRAC'},
  {src:'Low-temperature stress dissipating ability', dst:'FRAC'},
  {src:'Low-temperature tensile strength', dst:'FRAC'},
  {src:'Marshall flow value', dst:'FRAC'},
  {src:'Marshall quotient', dst:'FRAC'},
  {src:'Marshall stability', dst:'AC'},
  {src:'Marshall stability', dst:'FRAC'},
  {src:'Maximum bending strain', dst:'FRAC'},
  {src:'Maximum bending stress', dst:'FRAC'},
  {src:'Maximum strain', dst:'FRAC'},
  {src:'Maximum tensile strain', dst:'FRAC'},
  {src:'Mechanical properties', dst:'FRAC'},
  {src:'Midspan deflection', dst:'FRAC'},
  {src:'Moisture damage resistance', dst:'FRAC'},
  {src:'Moisture susceptibility', dst:'AC'},
  {src:'Moisture susceptibility', dst:'FRAC'},
  {src:'Pavement performance', dst:'FRAC'},
  {src:'Permanent deformation', dst:'FRAC'},
  {src:'Permeability resistance', dst:'FRAC'},
  {src:'Phase angle', dst:'FRAC'},
  {src:'Reflective crack resistance', dst:'FRAC'},
  {src:'Resilient modulus', dst:'FRAC'},
  {src:'Retained marshall stability', dst:'FRAC'},
  {src:'Rheological properties', dst:'FRAC'},
  {src:'Rutting resistance', dst:'AC'},
  {src:'Rutting resistance', dst:'FRAC'},
  {src:'Self-healing ability', dst:'FRAC'},
  {src:'Service life', dst:'FRAC'},
  {src:'Shear strength', dst:'FRAC'},
  {src:'Stiffness modulus', dst:'AC'},
  {src:'Stiffness modulus', dst:'FRAC'},
  {src:'Stress concentration', dst:'FRAC'},
  {src:'Stripping resistance', dst:'FRAC'},
  {src:'Sustainable application', dst:'FRAC'},
  {src:'Temperature stability', dst:'FRAC'},
  {src:'Tensile crack resistance', dst:'FRAC'},
  {src:'Tensile strain', dst:'FRAC'},
  {src:'Tensile strength', dst:'FRAC'},
  {src:'Tensile strength ratio', dst:'FRAC'},
  {src:'Thermal conductivity', dst:'FRAC'},
  {src:'Thermal crack resistance', dst:'AC'},
  {src:'Thermal crack resistance', dst:'FRAC'},
  {src:'Toughness', dst:'FRAC'},
  {src:'Viscoelastic properties', dst:'FRAC'},
  {src:'Viscoplastic strain', dst:'FRAC'},
  {src:'Viscosity', dst:'FRAC'},
  {src:'Voids filled with bitumen', dst:'AC'},
  {src:'Voids in mineral aggregate', dst:'AC'},
  {src:'Voids in mineral aggregate', dst:'FRAC'}
] AS row
MATCH (a:`PerformanceProperty` {name: row.src})
MATCH (b:`Mix` {name: row.dst})
MERGE (a)-[:`Property_of`]->(b);
